// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {

  /// Get the correct Firebase configuration based on the platform (Web, Android, iOS)
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) { // Agar app web par chal rahi hai
      return web;
    }
    switch (defaultTargetPlatform) { // Agar mobile ya desktop par
      case TargetPlatform.android: // Android ke liye config
        return android;
      case TargetPlatform.iOS: // iOS ke liye config
        return ios;
      case TargetPlatform.macOS: // macOS ke liye agar config nahi hai
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows: // Windows ke liye agar config nahi hai
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux: // Linux ke liye agar config nahi hai
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default: // Agar unknown platform ho
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// 🔹 Web Firebase config
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZpGqNrZdOqnDQ6L6I4qX3E5cBTlulbC0', // API key
    appId: '1:41261936226:web:14347209f0c0207dff2b3b', // App ID
    messagingSenderId: '41261936226', // Messaging/Push notifications ID
    projectId: 'mindease-98af9', // Firebase project ID
    authDomain: 'mindease-98af9.firebaseapp.com', // Auth domain for web
    storageBucket: 'mindease-98af9.firebasestorage.app', // Storage bucket
    measurementId: 'G-FV3ZC205JM', // Analytics measurement ID
  );

  /// 🔹 Android Firebase config
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEADQ8Wxw-paDbObqoQuUxNJOvHtyfBJw', // API key
    appId: '1:41261936226:android:f599b76cba6fa2e1ff2b3b', // App ID
    messagingSenderId: '41261936226', // Messaging/Push notifications ID
    projectId: 'mindease-98af9', // Firebase project ID
    storageBucket: 'mindease-98af9.firebasestorage.app', // Storage bucket
  );

  /// 🔹 iOS Firebase config
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLKWcZ4zD1Hh9xIkOb7J-dZk6WPU8EszY', // API key
    appId: '1:41261936226:ios:5bed373e40573bfcff2b3b', // App ID
    messagingSenderId: '41261936226', // Messaging/Push notifications ID
    projectId: 'mindease-98af9', // Firebase project ID
    storageBucket: 'mindease-98af9.firebasestorage.app', // Storage bucket
    iosBundleId: 'com.example.mindease', // iOS app bundle ID
  );
}